language: node_js
node_js: 12.9.0
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: CX2uGVyPdN3x4jrx3opFShrc13czWzXB93f4cOjEN+/QL4dQfvwa6a3BFCUlqu2/hcn8M+JxghHNAEMdEbOjReWgQ2DtH5hsrLiN+GEERFs8+EIDKTaHrZynKtYsl61gOWkVypdcOgA9O5c11UCZIp0bD0opGA9LUFL9Q/18yPTn7oagZKhaAxW8jCDw6NL5TsqqYQofixaNGbINikdwHkdsbKhkYFPNzUOXFCTzBiRFbmn6lwVv8nJ1RJjoEx4LJ+d3BSkp4u/s4kW4e+Brm6+EJdnY3KS4YpiiGaCApsR34ia5HlV8RNUxS5ohQqhtpndgeju7Db3pdX5RWSGUcOh82FFxPay6xsmciNTcQvbIqo0KAw4f4ESuF5OnZBWFzPvPfAo5xd2qvQPiFCtGpd4RvCgnNjcpH+6xEGPIWwuqaV+Nw4Ac3yg0CGrhEUy9GBbqJl3yLUCpLM5dK4cGLUZYHYmhHTq9AtVWYArJMps0ftMFkRc1DHDFBGe9cJkYeut1N1Nl9XWTgg/8TzpfAou7YdkyzOFsvQdBSFXk32FasibNvaJyQaMliXKopccFcZvk2q3ZurUO5V8HLpi20jO6i3y0P1rK1keAGVyscsnxugsIYdCcNNU6ADJE8rZXAlXV0peJWSh46iijVS1GG6UBx/zBk4ADcMS88kcklHY=
  app: travisreact
  on:
    repo: christianahvilla/travis
true:
  branche: master
